"""unique制約を削除

Revision ID: e96b7a13ec22
Revises: f1dab41771e0
Create Date: 2026-04-28 20:11:53.392994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96b7a13ec22'
down_revision = 'f1dab41771e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memo', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('memo_user_id_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memo', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('memo_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
